In [1]:
import pandas as pd
import psycopg2
# Для подавления сообщений об ошибках при обработке pandas ответов psycopg2
import warnings
warnings.filterwarnings('ignore')

DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [2]:
DBNAME = 'skillfactory'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [3]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

In [4]:
n=10
query = f'''select *
            from sql.pokemon
            limit {n}
        '''

In [5]:
df = pd.read_sql_query(query, connection)
df

   id                       name  type1   type2  hp  attack  defense  speed
0   1                  Bulbasaur  Grass  Poison  45      49       49     45
1   2                    Ivysaur  Grass  Poison  60      62       63     60
2   3                   Venusaur  Grass  Poison  80      82       83     80
3   4      VenusaurMega Venusaur  Grass  Poison  80     100      123     80
4   7                  Charizard   Fire  Flying  78      84       78    100
5   8  CharizardMega Charizard X   Fire  Dragon  78     130      111    100
6   9  CharizardMega Charizard Y   Fire  Flying  78     104       78    100
7  16                 Butterfree    Bug  Flying  60      45       50     70
8  17                     Weedle    Bug  Poison  40      35       30     50
9  18                     Kakuna    Bug  Poison  45      25       50     35